### ISSUE TITLE
Has this module been tested with Sitecore 9?

### ISSUE THREAD

**Issue by hhog-tkamin** [buildabonfire/Bonfire-Company-Personalization#1]

**Comment by dnstommy** [comment]
No. At Symposium we got a lot of interest in this component again. We are rewriting it for Sitecore 9 right now. It will be Sitecore 9.0.2 and 9.1

**Comment by hhog-tkamin** [comment]
Awesome! Thanks for the quick update and I look forward to seeing the updates for SC9.
